# .github/workflows/cat_fact_action.yml
name: Cat Fact Action
on: [push]

jobs:
  get-cat-fact:
    runs-on: ubuntu-latest
    name: Gets a random cat fact
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get cat fact
        id: get_cat_fact
        uses: ./
      - name: Print the cat fact
        run: echo "${{ steps.get_cat_fact.outputs.cat_fact }}"
